[account]
# Configuration of account and connection

rpc_url_env = "RPC_URL"
wallet_address_env = "WALLET_ADDRESS"
password_path_env = "KEYSTORE_PWD_PATH"
keystore_path_env = "KEYSTORE_PATH"

[asset]
# Market configuration goes here - what and where are we trading
base_asset = "STRK"
quote_asset = "USDC"

# TODO: This is currently remus specific
market_id = 2

price_source = 'binance'

# TODO: add `net` (where are we trading) here  
# TODO: add `venue` (on what venue are we trading) here 

[reconciler]
name = 'bounded_reconciler'
max_relative_distance_from_fp = "0.075" # too far from FP to be considered best (it is considered deep)
min_relative_distance_from_fp = "0.0005" # too close to FP to exist -> if closer kill the order
minimal_remaining_size = "0"  # in Base asset (human-readable)
max_orders_per_side = 1

[[orderchain]]
name = 'fixed_params'
target_relative_distance_from_fp = "0.005" # where best order is created 
order_size_quote = "10"   # in Quote asset (human-readable)
