[account]
# Configuration of account and connection

rpc_url_env = "RPC_URL"
wallet_address_env = "WALLET_ADDRESS"
password_path_env = "KEYSTORE_PWD_PATH"
keystore_path_env = "KEYSTORE_PATH"

[market]
venue = 'remus'
market_id = 2  # market_id is an internal identifier of a market.

[price_source]
base_asset = "STRK"
quote_asset = "USDC"
price_source = 'binance'

[reconciler]
name = "tolerance_reconciler"
relative_price_tolerance = "0.0002"
relative_quantity_tolerance = "0.01"

[tx_builder]
name = 'bundling_tx_builder'  # Transaction builder. For example "bundling_tx_builder" bundles transactions into a multicall.

[[orderchain]]
name = 'skew_fair_price_on_position'
bias = '0.005'
max_skew = '0.002'

[[orderchain]]
name = 'fixed_params'
target_relative_distance_from_fp = "0.005"  # Where best order is created
order_size_quote = "1"  # In Quote asset (human-readable)

[[min_max_relative_distance]]
max_relative_distance_from_fp = "0.075" # Threshold for an order to be considered too far from FP to be best order
min_relative_distance_from_fp = "0.0005" # Threshold for an order to be considered too close to FP to exist

[[orderchain]]
name = 'remove_orders_on_low_inventory'
