services:
  remus-eth-usdc:
   image: market-maker:0.6.0
   env_file:
     - ${HOME}/.keystores/.env-eth-usdc
   secrets:
     - keystore-remus-eth-usdc
     - pwd-remus-eth-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-remus-eth-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-eth-usdc
   ports:
     - 8001:8000
   command: ["--cfg", "./strats/remus_eth_usdc.toml"]

  remus-strk-usdc:
   image: market-maker:0.6.0
   env_file:
     - ${HOME}/.keystores/.env-strk-usdc
   secrets:
     - keystore-remus-strk-usdc
     - pwd-remus-strk-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-remus-strk-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-strk-usdc
   ports:
     - 8002:8000
   command: ["--cfg", "./strats/remus_strk_usdc.toml"]

  remus-wbtc-usdc:
   image: market-maker:0.6.0
   env_file:
     - ${HOME}/.keystores/.env-wbtc-usdc
   secrets:
     - keystore-remus-wbtc-usdc
     - pwd-remus-wbtc-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-remus-wbtc-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-wbtc-usdc
   ports:
     - 8003:8000
   command: ["--cfg", "./strats/remus_wbtc_usdc.toml"]

  remus-wbtc-dog:
    image: market-maker:0.6.0
    env_file:
      - ${HOME}/.keystores/.env-dog-wbtc
    secrets:
      - keystore-remus-wbtc-dog
      - pwd-remus-wbtc-dog
    environment:
      - KEYSTORE_PATH=/run/secrets/keystore-remus-wbtc-dog
      - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-wbtc-dog
    ports:
      - 8004:8000
    command: ["--cfg", "./strats/remus_wbtc_dog.toml"]


  ekubo-eth-usdc:
   image: market-maker:0.6.0
   env_file:
     - ${HOME}/.keystores/.env-ekubo-eth-usdc
   secrets:
     - keystore-ekubo-eth-usdc
     - pwd-wkubo-eth-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-ekubo-eth-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-ekubo-eth-usdc
   ports:
     - 8005:8000
   command: ["--cfg", "./strats/ekubo_eth_usdc.toml"]

  ekubo-strk-usdc:
   image: market-maker:0.6.0
   env_file:
     - ${HOME}/.keystores/.env-ekubo-strk-usdc
   secrets:
     - keystore-ekubo-strk-usdc
     - pwd-ekubo-strk-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-ekubo-strk-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-ekubo-strk-usdc
   ports:
     - 8006:8000
   command: ["--cfg", "./strats/ekubo_strk_usdc.toml"]

  ekubo-wbtc-usdc:
   image: market-maker:0.6.0
   env_file:
     - ${HOME}/.keystores/.env-ekubo-wbtc-usdc
   secrets:
     - keystore-ekubo-wbtc-usdc
     - pwd-ekubo-wbtc-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-ekubo-wbtc-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-ekubo-wbtc-usdc
   ports:
     - 8007:8000
   command: ["--cfg", "./strats/ekubo_wbtc_usdc.toml"]

  ekubo-wbtc-dog:
    image: market-maker:0.6.0
    env_file:
      - ${HOME}/.keystores/.env-ekubo-dog-wbtc
    secrets:
      - keystore-ekubo-wbtc-dog
      - pwd-ekubo-wbtc-dog
    environment:
      - KEYSTORE_PATH=/run/secrets/keystore-ekubo-wbtc-dog
      - KEYSTORE_PWD_PATH=/run/secrets/pwd-ekubo-wbtc-dog
    ports:
      - 8008:8000
    command: ["--cfg", "./strats/ekubo_wbtc_dog.toml"]

secrets:
  keystore-remus-wbtc-dog:
    external: true
  pwd-remus-wbtc-dog:
    external: true
  keystore-remus-eth-usdc:
    external: true
  pwd-remus-eth-usdc:
    external: true
  keystore-remus-strk-usdc:
    external: true
  pwd-remus-strk-usdc:
    external: true
  keystore-remus-wbtc-usdc:
    external: true
  pwd-remus-wbtc-usdc:
    external: true

  keystore-ekubo-wbtc-dog:
    external: true
  pwd-ekubo-wbtc-dog:
    external: true
  keystore-ekubo-eth-usdc:
    external: true
  pwd-ekubo-eth-usdc:
    external: true
  keystore-ekubo-strk-usdc:
    external: true
  pwd-ekubo-strk-usdc:
    external: true
  keystore-ekubo-wbtc-usdc:
    external: true
  pwd-ekubo-wbtc-usdc:
    external: true