services:
  remus-eth-usdc:
   image: market-maker:0.4.0
   env_file:
     - ${HOME}/.keystores/.env-eth-usdc
   secrets:
     - keystore-remus-eth-usdc
     - pwd-remus-eth-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-remus-eth-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-eth-usdc
   ports:
     - 8001:8000
   command: ["--cfg", "./strats/remus_eth_usdc.toml"]

  remus-strk-usdc:
   image: market-maker:0.4.0
   env_file:
     - ${HOME}/.keystores/.env-strk-usdc
   secrets:
     - keystore-remus-strk-usdc
     - pwd-remus-strk-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-remus-strk-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-strk-usdc
   ports:
     - 8002:8000
   command: ["--cfg", "./strats/remus_strk_usdc.toml"]

  remus-wbtc-usdc:
   image: market-maker:0.4.0
   env_file:
     - ${HOME}/.keystores/.env-wbtc-usdc
   secrets:
     - keystore-remus-wbtc-usdc
     - pwd-remus-wbtc-usdc
   environment:
     - KEYSTORE_PATH=/run/secrets/keystore-remus-wbtc-usdc
     - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-wbtc-usdc
   ports:
     - 8003:8000
   command: ["--cfg", "./strats/remus_wbtc_usdc.toml"]

  remus-wbtc-dog:
    image: market-maker:0.4.0
    env_file:
      - ${HOME}/.keystores/.env-dog-wbtc
    secrets:
      - keystore-remus-wbtc-dog
      - pwd-remus-wbtc-dog
    environment:
      - KEYSTORE_PATH=/run/secrets/keystore-remus-wbtc-dog
      - KEYSTORE_PWD_PATH=/run/secrets/pwd-remus-wbtc-dog
    ports:
      - 8004:8000
    command: ["--cfg", "./strats/remus_wbtc_dog.toml"]


secrets:
  keystore-remus-wbtc-dog:
    external: true
  pwd-remus-wbtc-dog:
    external: true
  keystore-remus-eth-usdc:
    external: true
  pwd-remus-eth-usdc:
    external: true
  keystore-remus-strk-usdc:
    external: true
  pwd-remus-strk-usdc:
    external: true
  keystore-remus-wbtc-usdc:
    external: true
  pwd-remus-wbtc-usdc:
 